name: Jekyll Deploy

on:
  push:
    branches:
      - feature/update-hj

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"
      - name: Bundler Cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install bundler
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install
      - name: Build & Deploy to GitHub Pages
        run: |
          DEST="${JEKYLL_DESTINATION:-_site}"
          REPO="https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          BRANCH="gh-pages"
          echo "Building Jekyll site..."
          JEKYLL_ENV=production bundle exec jekyll build
          
          echo "Publishing..."
          cd ${DEST}
          git init
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "published by GitHub Actions"
          git push --force ${REPO} master:${BRANCH}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
